# GitHub Configuration
github:
  # GitHub Enterprise name (required)
  enterprise: "your_enterprise_name"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/populate_cost_centers.log"

# Cost Center Configuration
cost_centers:
  # Manual cost center IDs (only needed when auto_create is false)
  no_prus_cost_center_id: "REPLACE_WITH_NO_PRUS_COST_CENTER_ID"
  prus_allowed_cost_center_id: "REPLACE_WITH_PRUS_ALLOWED_COST_CENTER_ID"
  
  # Users who should get access to PRU overages (always required)
  prus_exception_users: []
    # - "alice"
    # - "bob"
  
  # Auto-creation settings (creates cost centers if they don't exist)
  auto_create: true  # Set to false to use existing cost center IDs above
  
  # Cost center names (only used when auto_create is true)
  no_prus_cost_center_name: "00 - No PRU overages"  # Name for no-PRU cost center
  prus_allowed_cost_center_name: "01 - PRU overages allowed"  # Name for PRU-allowed cost center