name: GitHub Copilot Cost Center Automation

on:
  schedule:
    # Run every 6 hours (adjust as needed)
    - cron: '0 */6 * * *'
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:
    inputs:
      mode:
        description: 'Run mode'
        required: true
        default: 'incremental'
        type: choice
        options:
          - incremental
          - full

jobs:
  update-cost-centers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Create environment file
      run: |
        echo "GITHUB_TOKEN=${{ secrets.COPILOT_GITHUB_TOKEN }}" > .env
        echo "GITHUB_ENTERPRISE=${{ secrets.GITHUB_ENTERPRISE_NAME }}" >> .env
    
    - name: Update config with secrets
      run: |
        sed -i 's/REPLACE_WITH_ENTERPRISE_SLUG/${{ secrets.GITHUB_ENTERPRISE_NAME }}/g' config/config.yaml
        sed -i 's/REPLACE_WITH_NO_PRU_COST_CENTER_ID/${{ secrets.NO_PRU_COST_CENTER_ID }}/g' config/config.yaml
        sed -i 's/REPLACE_WITH_PRU_COST_CENTER_ID/${{ secrets.PRU_COST_CENTER_ID }}/g' config/config.yaml
    
    - name: Run incremental cost center update
      if: github.event.inputs.mode != 'full'
      run: |
        python main.py --create-cost-centers --assign-cost-centers --incremental --mode apply --yes --summary-report --verbose
    
    - name: Run full cost center update  
      if: github.event.inputs.mode == 'full'
      run: |
        python main.py --create-cost-centers --assign-cost-centers --mode apply --yes --summary-report --verbose
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cost-center-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30
    
    - name: Check for failures and notify
      if: failure()
      run: |
        echo "::error::Cost center automation failed. Check the logs for details."